spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      ##naming:
      ##  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
#添加log配置
logging:
  path: /user/local/log
  level:
    com:
      yyz: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: ERROR
